server:
  port: 0
  shutdown: graceful
spring:
  profiles:
    active: docker
  application:
    name: goodskill-oauth2-client
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 6d0f6a3569e8511284253bbf33d6ac94092651fe8cfc1ef98cfe1ac4dd5c5da6
            client-secret: 215acada1f3e4692ed25e25a73978a847357af9547a5b9227164367e5f7ab65e

dubbo:
  protocol:
    name: dubbo
    port: -1
    id: dubbo
  scan:
    base-packages: com.goodskill.mongo.service
  cloud:
    subscribed-services: ""
  provider:
    timeout: 30000
logging:
  level:
    org:
      springframework:
        data:
          mongodb: debug

---
spring:
  cloud:
    nacos:
      server-addr: nacos:8848
    sentinel:
      datasource:
        ds0:
          nacos:
            server-addr: nacos:8848
  config:
    activate:
      on-profile: docker
dubbo:
  registry:
    address: spring-cloud://localhost
