spring:
  profiles:
    active: local
  application:
    name: dubbo-provider-demo
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      database: test
---
cache_address: localhost
cache_ip_address: redis://127.0.0.1:6379
master:
  driver: com.mysql.cj.jdbc.Driver
  password: +tkfyiKcqLiFlgt7GSnxtw==
  url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: root
mq_address: failover:(tcp://localhost:61616)?initialReconnectDelay=100
slave:
  driver: com.mysql.cj.jdbc.Driver
  password: +tkfyiKcqLiFlgt7GSnxtw==
  url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  username: root
zookeeper_ip: localhost:12345
---
dubbo:
  scan:
    base-packages: org.seckill.service.impl
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
    qos-port: 22222
    qos-enable:  true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: my-registry
    address: N/A
---
demo:
  service:
    version: 1.0.0
---
server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
#二维码图片存放目录
QRCODE_IMAGE_DIR: C:/Users/27568/Desktop/QRfile