spring:
  profiles:
    active: dev
  application:
    name: es-service-provider
## dubbo服务注册和发现
dubbo:
  protocol:
    name: dubbo
    port: -1
    id: dubbo
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.goodskill.es.service
  cloud:
    subscribed-services: "*"
## 日志级别
logging:
  level:
    org:
      elasticsearch:
        client:
          RestClient: debug
## es客户端配置
elasticsearch:
  rest:
    client:
      address: localhost:9200
---
spring:
  profiles: dev
dubbo:
  registry:
    address: spring-cloud://localhost
elasticsearch:
  rest:
    client:
      address: localhost:9200
---
spring:
  profiles: docker
dubbo:
  registry:
    address: spring-cloud://localhost
elasticsearch:
  rest:
    client:
      address: elasticsearch:9200
