spring:
  profiles:
    active: dev
  application:
    name: mongo-service-provider
demo:
  service:
    version: 1.0.0
dubbo:
  protocol:
    name: dubbo
    port: -1
    id: dubbo
  scan:
    base-packages: com.goodskill.mongo.service
  cloud:
    subscribed-services: ""
---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://127.0.0.1:61616
  data:
    mongodb:
      database: test
dubbo:
  registry:
    address: spring-cloud://localhost
---
spring:
  profiles: docker
  activemq:
    broker-url: tcp://activemq:61616
  data:
    mongodb:
      database: test
      uri: mongodb://mongo
dubbo:
  registry:
    address: spring-cloud://localhost