server:
  port: 19091

spring:
  profiles:
    active: dev
  application:
    name: mongo-service-provider
demo:
  service:
    version: 1.0.0
dubbo:
  protocol:
    name: dubbo
    port: -1
    id: dubbo
  scan:
    base-packages: com.goodskill.mongo.service
  cloud:
    subscribed-services: ""


---
spring:
  profiles: dev
  activemq:
    broker-url: tcp://127.0.0.1:61616
  data:
    mongodb:
      database: test
  cloud:
    nacos:
      server-addr: localhost:8848
dubbo:
  registry:
    address: spring-cloud://localhost
---
spring:
  profiles: docker
  activemq:
    broker-url: tcp://activemq:61616
  data:
    mongodb:
      database: test
      uri: mongodb://mongo
  cloud:
    nacos:
      server-addr: nacos:8848
dubbo:
  registry:
    address: spring-cloud://localhost
---
spring:
  profiles: test
  activemq:
    broker-url: tcp://192.168.2.22:61616
  data:
    mongodb:
      database: test
      host: 192.168.2.22
  cloud:
    nacos:
      server-addr: 192.168.2.22:8848
dubbo:
  registry:
    address: spring-cloud://192.168.2.22