spring:
  profiles:
    active: dev
  application:
    name: goodskill-web
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
    store-type: redis
    timeout: 1800
  main:
    allow-bean-definition-overriding: true
  activemq:
    in-memory: true
    pool:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    sentinel:
      transport:
        port: 8719
        ## 默认端口8080，已改为自定义18088端口，通过http://127.0.0.1:18088/#/dashboard访问
        dashboard: localhost:18088

application:
  message: Hello

dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  consumer:
    timeout: 30000
  ## 此处有坑，如配置了具体的service名，对应的注入此service上的注解@Reference(check=false)会失效
  cloud:
    subscribed-services: "*"

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8080
  servlet:
    context-path: /goodsKill

#二维码图片存放目录
QRCODE_IMAGE_DIR: D:/QRfile
---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      repositories:
        enabled: true
dubbo:
  registry:
    address: spring-cloud://localhost

mq_address: failover:(tcp://localhost:61616)?initialReconnectDelay=100


---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  cloud:
    nacos:
      server-addr: nacos:8848
  kafka:
    bootstrap-servers: kafka:9092
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
dubbo:
  registry:
    address: spring-cloud://localhost
mq_address: failover:(tcp://activemq:61616)?initialReconnectDelay=100
